### ISSUE TITLE
missing headers?

### ISSUE THREAD

**Issue by smdprutser** [dmitrystu/sboot_stm32#1]
during compile I get this error:

src/descriptors.c:19:19: fatal error: stm32.h: No such file or directory 
 #include "stm32.h"

I think I'm missing a required dependency.

**Comment by dmitrystu** [comment]
Sure. Take it [here](https://github.com/dmitrystu/stm32h).

**Comment by davidgfnet** [comment]
That's not mentioned in the docs right? Also, why is it in another repo? Would be nice if it was set up as a subrepo so it gets pulled too.

**Comment by dmitrystu** [comment]
Sorry for the later reply.
I see no way to do this because stm32.h is related to CMSIS root, not a project root.
