### ISSUE TITLE
DATA_EEPROM_END undefined error

### ISSUE THREAD

**Issue by frazerbarnes** [dmitrystu/sboot_stm32#12]
I am building for the STM32L072KZ. When attempting to build using the provided config.h with cipher disabled. I get DATA_EEPROM_END undefined as an error. Are there any other definitions I need to add to the config.h

**Comment by dmitrystu** [comment]
I need to check EEPROM configuration and defines for this MCU. If you don't need EEPROM programming interface you can disable it in config.h
```c
#define DFU_INTF_EEPROM     _DISABLE
```

**Comment by dmitrystu** [comment]
Could you please check [This](https://github.com/dmitrystu/sboot_stm32/tree/fix/32L0x2bc-EEPROM)  fix for the L0x2 devices with 6K EEPROM.
