### ISSUE TITLE
User firmware stuck or not starting after reset.

### ISSUE THREAD

**Issue by curiousmindsdev** [dmitrystu/sboot_stm32#26]
I have a demo firmware toggling 6 LEDs in sequence. I uploaded it using dfu-util but it does not start. First LED turns on and it stops there. I'm guessing that I forgot to add something in my code. DFU_APP_START is set to 0x08001000 and DFU_APP_SIZE is set to 126976 in config file. Also I set  `FLASH    (rx)    : ORIGIN = 0x08001000,   LENGTH = 124K` in my demo project. I've uploaded my demo project along with `bootloader.map` and `config.h` file to Google Drive. Can you check if something is wrong? 

https://drive.google.com/drive/folders/17VR4t5-j2v8Tgzqlx1nVWkIIFzimskdh?usp=sharing

**Comment by dmitrystu** [comment]
Tried to debug with your code. I was surprised that F0 series doesn't support ISR table relocation. I see no way to fix this.

**Comment by dmitrystu** [comment]
Probably I have found a solution. But it needs to be tested.

**Comment by dmitrystu** [comment]
Could you test with [this](https://github.com/dmitrystu/sboot_stm32/tree/fix/F0_ISR) branch?
In a few words, since if we can't set a VTOR we must handle ISR in the bootloader then do a jump to the application ISR.

**Comment by curiousmindsdev** [comment]
IT WORKED!!! Thank you so much!!!

**Comment by dzarda** [comment]
Nice solution. I think we want to have this merged
