### ISSUE TITLE
Clear FLASH_SR in stm32f0xx.S

### ISSUE THREAD

**Issue by alexispolti** [dmitrystu/sboot_stm32#45]
I might be wrong but I have some doubts about the way to clear the FLASH_SR in `mcu/stm32f00x.S`.
Current code is (line 397)
```asm
/* clear FLASH_SR */
    movs    r4, 0x64
    str     r4, [r3, FLASH_SR]
```
But looking at stm32f072v8 and stm32f0x1stm32f0x2stm32f0x8 reference manuals, the correct value to write should be 0x34 (or 0x14) if I'm not mistaken. Did I miss something?

**Comment by dmitrystu** [comment]
Yes, it must be a copypaste. Anyway, it will clear EOP, but must be fixed.
